"""Stable public facade for registry and planning services."""

from kammat.main.plan_format import (
    format_plan_json,
    format_plan_text,
    plan_to_primitive,
)
from kammat.main.pipeline import (
    ArtifactObservation,
    ArtifactResolution,
    ArtifactSnapshot,
    ExecutionPlan,
    OBSERVATION_STATES,
    PLAN_ISSUE_CATALOG,
    PlanIssue,
    PlanResult,
    PlanSelection,
    PlannedStage,
    build_plan,
    inspect_plan_artifacts,
)
from kammat.main.stages import (
    ARTIFACT_KINDS,
    ArtifactSpec,
    PathBinding,
    REQUIREMENT_POLICIES,
    RegistryError,
    STAGES,
    STAGE_BY_NAME,
    STAGE_NAMES,
    StageSpec,
    stage_registry,
)

__all__ = [
    "ARTIFACT_KINDS",
    "ArtifactObservation",
    "ArtifactResolution",
    "ArtifactSnapshot",
    "ArtifactSpec",
    "ExecutionPlan",
    "OBSERVATION_STATES",
    "PLAN_ISSUE_CATALOG",
    "PathBinding",
    "PlanIssue",
    "PlanResult",
    "PlanSelection",
    "PlannedStage",
    "REQUIREMENT_POLICIES",
    "RegistryError",
    "STAGES",
    "STAGE_BY_NAME",
    "STAGE_NAMES",
    "StageSpec",
    "build_plan",
    "format_plan_json",
    "format_plan_text",
    "inspect_plan_artifacts",
    "plan_to_primitive",
    "stage_registry",
]
